In [70]:
import pandas as pd

In [122]:
dados = pd.read_excel('/content/drive/MyDrive/PROGRAMARIA/Python/analise_dados_mod7.xlsx')

In [123]:
dados.head()

,ID,IDADE,FAIXA IDADE,GENERO,COR/RACA/ETNIA,PCD,EXPERIENCIA_PROFISSIONAL_PREJUDICADA,ASPECTOS_PREJUDICADOS,VIVE_NO_BRASIL,ESTADO ONDE MORA,...,Você pretende mudar de emprego nos próximos 6 meses?,Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?,Atualmente qual a sua forma de trabalho?,Qual a forma de trabalho ideal para você?,Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?,Sua empresa passu por Layoff em 2022?,Atuacao,Quais das linguagens listadas abaixo você utiliza no trabalho?,EM_BUSCA,ABERTO_OPORTUNIDADES
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,39.0,35-39,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,NaN,True,Distrito Federal (DF),...,Não estou buscando e não pretendo mudar de emp...,Benefícios,Modelo 100% presencial,Modelo híbrido com dias fixos de trabalho pres...,Vou aceitar e retornar ao modelo 100% presencial,Não ocorreram layoffs/demissões em massa na em...,Engenharia de Dados,SQL,0.0,0.0
1,zzls2oftfn9law393oezzls2ofhvfpzd,32.0,30-34,Masculino,Parda,Não,"Sim, acredito que a minha a experiência profis...",Aprovação em processos seletivos/entrevistas,True,Pará (PA),...,Estou em busca de oportunidades dentro ou fora...,"Remuneração/Salário, Plano de carreira e oport...",Modelo 100% presencial,Modelo híbrido flexível (o funcionário tem lib...,Vou aceitar e retornar ao modelo 100% presencial,Não ocorreram layoffs/demissões em massa na em...,Gestor,NaN,1.0,0.0
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,53.0,50-54,Masculino,Branca,Não,NaN,NaN,True,Distrito Federal (DF),...,"Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Flexibilidade de trabalho...",Modelo híbrido com dias fixos de trabalho pres...,Modelo híbrido flexível (o funcionário tem lib...,Vou procurar outra oportunidade no modelo híbr...,Não ocorreram layoffs/demissões em massa na em...,desenvolve modelos preditivos e algoritmos de ...,1,0.0,1.0
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,27.0,25-29,Masculino,Branca,Não,NaN,NaN,True,Minas Gerais (MG),...,"Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Flexibilidade de trabalho...",Modelo híbrido flexível (o funcionário tem lib...,Modelo híbrido flexível (o funcionário tem lib...,Vou procurar outra oportunidade no modelo híbr...,Não ocorreram layoffs/demissões em massa na em...,desenvolve modelos preditivos e algoritmos de ...,0,0.0,1.0
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,46.0,45-49,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,NaN,True,Pará (PA),...,"Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Oportunidade de aprendiza...",Modelo 100% presencial,Modelo 100% presencial,Vou aceitar e retornar ao modelo 100% presencial,Não ocorreram layoffs/demissões em massa na em...,Outra atuação,SQL,0.0,1.0

In [124]:
dados.columns

Index(['ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA', 'PCD',
       'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'UF ONDE MORA',
       'REGIAO ONDE MORA', 'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM',
       'NIVEL DE ENSINO', 'ÁREA DE FORMAÇÃO',
       'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO', 'NOVO_NIVEL', 'NIVEL_Júnior', 'NIVEL_Pleno', 'NIVEL_Sênior',
       'GEARACAO', 'Quanto tempo de experiência na área de dados você tem?',
       'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?',
       'Você está satisfeito na sua empresa atual?',
       'Qual o principal motivo da sua insatisfação com a empresa atual?',
       'Você participou de entrevistas de emprego nos últimos 6 meses?',
       'Você pretende mudar de emprego nos próximos 6 meses?',
       'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?',
       'Atualmente qual a sua forma de trabalho?',
       'Qual a forma de trabalho ideal para você?',
       'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?',
       'Sua empresa passu por Layoff em 2022?', 'Atuacao',
       'Quais das linguagens listadas abaixo você utiliza no trabalho?',
       'EM_BUSCA', 'ABERTO_OPORTUNIDADES'],
      dtype='object')

In [125]:
dados['QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?'].value_counts()

QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?
Empregado (CLT)                                                    2762
Empreendedor ou Empregado (CNPJ)                                    410
Desempregado, buscando recolocação                                  350
Estagiário                                                          188
Servidor Público                                                    156
Trabalho na área Acadêmica/Pesquisador                               86
Somente Estudante (graduação)                                        82
Vivo no Brasil e trabalho remoto para empresa de fora do Brasil      69
Vivo fora do Brasil e trabalho para empresa de fora do Brasil        46
Somente Estudante (pós-graduação)                                    44
Freelancer                                                           39
Prefiro não informar                                                 24
Desempregado e não estou buscando recolocação                        15
Name: count, dtype: int64

In [126]:
dados = dados[dados['QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?']=='Empregado (CLT)']

In [127]:
dados['QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?'].value_counts()

QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?
Empregado (CLT)    2762
Name: count, dtype: int64

In [128]:
dados['COR/RACA/ETNIA'].value_counts()

COR/RACA/ETNIA
Branca                  1805
Parda                    661
Preta                    181
Amarela                   85
Prefiro não informar      16
Outra                     10
Indígena                   4
Name: count, dtype: int64

In [129]:
lista_retirar = ['Prefiro não informar','Outra','Indígena']

In [130]:
dados = dados[~dados['COR/RACA/ETNIA'].isin(lista_retirar)]

In [131]:
dados['NAO BRANCA'] = dados['COR/RACA/ETNIA'].apply(lambda x: 'Não Branca' if x != 'Branca' else '0')

In [132]:
dados['QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?'].value_counts()

QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?
de 1 a 2 anos                             743
de 3 a 4 anos                             584
de 4 a 6 anos                             416
Menos de 1 ano                            353
Mais de 10 anos                           277
de 7 a 10 anos                            232
Não tenho experiência na área de dados    127
Name: count, dtype: int64

In [133]:
dados ['TEMPO DE EXPERIENCIA']= dados['Quanto tempo de experiência na área de dados você tem?'].str.extract(r'(\d+)')

In [134]:
dados ['TEMPO DE EXPERIENCIA'].value_counts()

TEMPO DE EXPERIENCIA
1     1096
3      584
4      416
10     277
7      232
Name: count, dtype: int64

In [135]:
dados['NUMERO DE FUNCIONARIOS'].value_counts()

NUMERO DE FUNCIONARIOS
Acima de 3.000      1313
de 101 a 500         503
de 1.001 a 3.000     368
de 501 a 1.000       248
de 51 a 100          146
de 11 a 50           112
de 6 a 10             24
de 1 a 5              18
Name: count, dtype: int64

In [136]:
dados['NUMERO DE FUNCIONARIOS'] = dados['NUMERO DE FUNCIONARIOS'].str.replace('.','')

In [137]:
dados ['NUMERO DE FUNCIONARIOS']= dados['NUMERO DE FUNCIONARIOS'].str.extract(r'(\d+)')

In [139]:
dados['TEMPO DE EXPERIENCIA'].value_counts(dropna=False)

TEMPO DE EXPERIENCIA
1      1096
3       584
4       416
10      277
7       232
NaN     127
Name: count, dtype: int64

In [140]:
dados['TEMPO DE EXPERIENCIA'] = dados['TEMPO DE EXPERIENCIA'].fillna(0)

In [141]:
dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].value_counts()

Qual o principal motivo da sua insatisfação com a empresa atual?
Gostaria de trabalhar em em outra área de atuação                                                                                                           69
Salário atual não corresponde ao mercado                                                                                                                    53
Falta de oportunidade de crescimento no emprego atual                                                                                                       46
Falta de maturidade analítica na empresa                                                                                                                    45
Falta de oportunidade de crescimento no emprego atual, Salário atual não corresponde ao mercado, Falta de maturidade analítica na empresa                   26
                                                                                                                                                            ..
O clima de trabalho/ambiente não é bom, Não tenho uma boa relação com meu líder/gestor, Gostaria de receber mais benefícios                                  1
Falta de organização nos processos internos                                                                                                                  1
Gostaria de receber mais benefícios, O clima de trabalho/ambiente não é bom, Falta de oportunidade de crescimento no emprego atual                           1
Gostaria de receber mais benefícios, Falta de oportunidade de crescimento no emprego atual, O clima de trabalho/ambiente não é bom                           1
Não tenho uma boa relação com meu líder/gestor, Falta de oportunidade de crescimento no emprego atual, Gostaria de trabalhar em em outra área de atuação     1
Name: count, Length: 174, dtype: int64

In [145]:
dados['INSATISFACAO'].value_counts()

INSATISFACAO
0    2453
1     279
Name: count, dtype: int64

In [142]:
dados['INSATISFACAO'] = 0

In [143]:
dados.loc[dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].notnull(), 'INSATISFACAO'] = dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].astype(str).apply(lambda x: 1 if 'Salário' in x else 0)

In [144]:
dados.loc[dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].notnull(), 'INSATISFACAO']

1       0
2       0
7       1
10      0
26      1
       ..
4227    0
4234    1
4238    0
4240    1
4270    1
Name: INSATISFACAO, Length: 661, dtype: int64

In [146]:
dados['NIVEL_DE_ENSINO_NUMEROCURSO'] = dados['NIVEL DE ENSINO'].apply(lambda x: 0 if x == 'Não tenho graduação formal' else
                                                                     1 if x == 'Estudante de Graduação' else
                                                                     2 if x == 'Graduação/Bacharelado' else
                                                                     3 if x == 'Pós-graduação' else
                                                                     4 if x == 'Mestrado' else
                                                                     5 if x == 'Doutorado ou Phd' else -1)

In [147]:
dados.columns

Index(['ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA', 'PCD',
       'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'UF ONDE MORA',
       'REGIAO ONDE MORA', 'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM',
       'NIVEL DE ENSINO', 'ÁREA DE FORMAÇÃO',
       'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO', 'NOVO_NIVEL', 'NIVEL_Júnior', 'NIVEL_Pleno', 'NIVEL_Sênior',
       'GEARACAO', 'Quanto tempo de experiência na área de dados você tem?',
       'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?',
       'Você está satisfeito na sua empresa atual?',
       'Qual o principal motivo da sua insatisfação com a empresa atual?',
       'Você participou de entrevistas de emprego nos últimos 6 meses?',
       'Você pretende mudar de emprego nos próximos 6 meses?',
       'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?',
       'Atualmente qual a sua forma de trabalho?',
       'Qual a forma de trabalho ideal para você?',
       'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?',
       'Sua empresa passu por Layoff em 2022?', 'Atuacao',
       'Quais das linguagens listadas abaixo você utiliza no trabalho?',
       'EM_BUSCA', 'ABERTO_OPORTUNIDADES', 'NAO BRANCA',
       'TEMPO DE EXPERIENCIA', 'INSATISFACAO', 'NIVEL_DE_ENSINO_NUMEROCURSO'],
      dtype='object')

In [152]:
dados = dados[['IDADE', 'GENERO', 'NAO BRANCA', 'TEMPO DE EXPERIENCIA', 'INSATISFACAO', 'SETOR', 'REGIAO ONDE MORA',
               'NIVEL DE ENSINO', 'NUMERO DE FUNCIONARIOS', 'SALARIO', 'NOVO_NIVEL']]

In [153]:
dados.columns

Index(['IDADE', 'GENERO', 'NAO BRANCA', 'TEMPO DE EXPERIENCIA', 'INSATISFACAO',
       'SETOR', 'REGIAO ONDE MORA', 'NIVEL DE ENSINO',
       'NUMERO DE FUNCIONARIOS', 'SALARIO', 'NOVO_NIVEL'],
      dtype='object')

In [156]:
# Rode isso numa célula antes para confirmar que o DataFrame existe
print(dados.shape)
print(dados.head())

(2732, 11)
   IDADE     GENERO  NAO BRANCA TEMPO DE EXPERIENCIA  INSATISFACAO  \
1   32.0  Masculino  Não Branca                    3             0
2   53.0  Masculino           0                    3             0
3   27.0  Masculino           0                    4             0
6   21.0  Masculino  Não Branca                    1             0
7   31.0   Feminino           0                    1             1

                            SETOR REGIAO ONDE MORA         NIVEL DE ENSINO  \
1                     Outra Opção            Norte   Graduação/Bacharelado
2              Finanças ou Bancos     Centro-oeste           Pós-graduação
3                Setor Automotivo          Sudeste        Doutorado ou Phd
6              Finanças ou Bancos          Sudeste  Estudante de Graduação
7  Tecnologia/Fábrica de Software              Sul   Graduação/Bacharelado

  NUMERO DE FUNCIONARIOS  SALARIO      NOVO_NIVEL
1                   3000   4695.0  Pessoa Gestora
2                   3000  14202.0           Pleno
3                   3000  15463.0          Sênior
6                   3000   4491.0          Júnior
7                      6   2704.0          Júnior

In [157]:
dados_dummies = pd.get_dummies(dados, columns=['GENERO', 'SETOR', 'NOVO_NIVEL', 'REGIAO ONDE MORA'], drop_first=True)

In [165]:
X = dados_dummies.drop('SALARIO', axis=1)
y = dados_dummies['SALARIO']

In [161]:
from sklearn.model_selection import train_test_split

In [162]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [163]:
from sklearn.preprocessing import StandardScaler

In [170]:
dados_dummies = pd.get_dummies(dados, columns=['GENERO', 'SETOR', 'NOVO_NIVEL', 'REGIAO ONDE MORA',
                                                'NAO BRANCA', 'TEMPO DE EXPERIENCIA',
                                                'NIVEL DE ENSINO', 'NUMERO DE FUNCIONARIOS'], drop_first=True)

X = dados_dummies.drop('SALARIO', axis=1)
y = dados_dummies['SALARIO']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [179]:
!git config --global user.email "jessycosta@gmail.com"
!git config --global user.name "JessCosta137"

In [181]:
!find /content/drive/MyDrive -name "regressao_linear.ipynb"

/content/drive/MyDrive/regressao_linear.ipynb

In [184]:
%cd /content/drive/MyDrive
!git add regressao_linear.ipynb
!git commit -m "Projeto regressão linear - PrograMaria"
!git branch -M main
!git remote set-url origin https://JessCosta137:SEU_TOKEN_AQUI@github.com/JessCosta137/regressao-linear.git
!git push -u origin main

/content/drive/MyDrive
[main (root-commit) 9077f21] Projeto regressão linear - PrograMaria
 1 file changed, 1 insertion(+)
 create mode 100644 regressao_linear.ipynb
remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/JessCosta137/regressao-linear.git/'

In [185]:
!git push https://JessCosta137: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@github.com/JessCosta137/regressao-linear.git main

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 11.88 KiB | 869.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/JessCosta137/regressao-linear.git
 * [new branch]      main -> main

In [186]:
%cd /content/drive/MyDrive
!git add regressao_linear.ipynb
!git commit -m "Corrigindo notebook"
!git push https://JessCosta137:SEU_TOKEN_AQUI@github.com/JessCosta137/regressao-linear.git main

/content/drive/MyDrive
[main 21e5ee8] Corrigindo notebook
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/JessCosta137/regressao-linear.git/'

In [187]:
# Apaga o .git da raiz do Drive para limpar
import shutil
shutil.rmtree('/content/drive/MyDrive/.git', ignore_errors=True)

In [189]:
import os
os.environ['GITHUB_TOKEN'] = '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'

In [191]:
%cd /content/drive/MyDrive
!git push -f https://JessCosta137:$GITHUB_TOKEN@github.com/JessCosta137/regressao-linear.git main

/content/drive/MyDrive
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 9.56 KiB | 279.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/JessCosta137/regressao-linear.git
 + 9646766...e4661da main -> main (forced update)